# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: The Baer Cave
subtitle: Exploring the Mystic Mountains of Data Sorcery, Mathemagics and Artistry
name: Baer Ververgaert
email: bgmj.ververgaert@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Blogging about my experiences with data science, using mathematics to back it up and posting the occasional poem or image.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://baerververgaert.github.io/" # the base hostname & protocol for your site, e.g. http://example.com
#twitter_username: jekyllrb
github_username:  BaerVervergaert
google-site-verification: google8add7be213fc8707.html


# Author
author:
  name     : "Baer Ververgaert"
  avatar   : "/assets/images/profile-photo.JPG"
  bio      : "Understanding the world, one bit at a time."
  location : "Nijmegen, Netherlands"
  url      : "https://baerververgaert.github.io/"

social:
  name: Baer Ververgaert
  links:
    - https://www.linkedin.com/in/baer-ververgaert-699500162/

# Collections
collections_dir: collections
collections:
        DataSorcery:
                output: true
        Mathemagics:
                output: true
        Artistry:
                output: true
        MathematicsArt:
                output: true
        PersonalBlogs:
                output: true

# Defaults
default:
        - scope:
                  path: ""
          values:
                  layout: "default"
                  author: "Baer Gerardus Marius Johan Ververgaert"
        - scope:
                  path: ""
                  type: "DataSorcery"
          values:
                  layout: "posts"
        - scope:
                  path: ""
                  type: "Mathemagics"
          values:
                  layout: "posts"
        - scope:
                  path: ""
                  type: "Artistry"
          values:
                  layout: "posts"
        - scope:
                  path: ""
                  type: "MathematicsArt"
          values:
                  layout: "posts"
        - scope:
                  path: ""
                  type: "PersonalBlogs"
          values:
                  layout: "posts"


# Build settings
#theme: minima
#remote_theme: "mmistakes/minimal-mistakes@4.24.0"
theme: minimal-mistakes-jekyll
plugins:
  - jekyll-feed
  - jekyll-include-cache
  - jekyll-seo-tag

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
